### ISSUE TITLE
arm64, aarch64, ARMv8, 64-bit ARM support

### ISSUE THREAD

**Issue by vielmetti** [cloudfleet/floating-dock#6]
Either in this project or a different one, provide the same level of support for arm64 (aarch64, ARMv8), 64-bit ARM.

**Comment by DoubleMalt** [comment]
The project itself is architecture agnostic. Moving it to aarch64 is only the matter of an environment variable.

I can think of several ways to tackle this:

### Setup [registry.]marina64.io (or similar domain)

__Pros__
- Clear separation
- Easy to setup
- Does not introduce additional complexity

__Cons__
- Doubles the work for build maintainers

### Only split the registry into armhf.registry.marina.io and aarch64.registry.marina.io

__Pros__
- Only one point to setup your image builds 

__Cons__
- Adds complexity to build process
- Base images available for armhf and aarch are not the same

**Comment by DoubleMalt** [comment]
After discussion the second variant seems more user friendly and the effort should be manageable

**Comment by DoubleMalt** [comment]
Implemented and deployed.

**Comment by DoubleMalt** [comment]
Implemented and deployed.

**Comment by vielmetti** [comment]
Hi @DoubleMalt where is this deployed?

**Comment by DoubleMalt** [comment]
It's deployed on https://marina.io
